### PR TITLE
fix: correct button texts

### LINKED ISSUE #194: แก้ไข text ในปุ่ม สส., สว., ครม. ด้านล่าง ของส่วนนักการเมือง, การลงมติ
**Describe the bug**
[ส่วนนักการเมือง] 
ปุ่มสีดำด้านล่าง แสดง Text ว่า ‘สส. ทั้งหมด’ / ‘สว. ทั้งหมด’ / ‘คณะรัฐมนตรี ทั้งหมด’ แต่เมื่อกดเข้าไป จะเจอข้อมูลเฉพาะ สส./สว./คณะรัฐมนตรี ชุดล่าสุดเท่านั้น

[ส่วนการลงมติ]
ปุ่มสีดำด้านล่าง ไม่มีการระบุว่า สส. ชุดที่ 26 และ สว. ชุดที่ 13 หมายถึงชุดปัจจุบัน

**To Reproduce**
[ส่วนนักการเมือง]
1. ไปที่ [หน้าหลัก](https://parliamentwatch.wevis.info/)
2. Scroll มาที่ส่วน นักการเมือง
3. See error: แถบสีดำด้านล่างแสดง Text ว่า  ‘สส. ทั้งหมด’ / ‘สว. ทั้งหมด’ / ‘คณะรัฐมนตรี ทั้งหมด’ 

[ส่วนการลงมติ]
1. ไปที่ [หน้าหลัก](https://parliamentwatch.wevis.info/)
2. Scroll มาที่ส่วน การลงมติ
3. See error: แถบสีดำด้านล่าง ไม่มีการระบุใน Text ว่าสื่อถึง สส. สว. ชุดปัจจุบัน

**Expected behavior**
[ส่วนนักการเมือง]
ปุ่มสีดำข้างล่าง ให้แสดง Text ว่า
1. สมาชิกสภาผู้แทนราษฎร (สส.) ชุดที่ 26 (ชุดปัจจุบัน)
2. สมาชิกวุฒิสภา (สว.) ชุดที่ 13 (ชุดปัจจุบัน)
3. คณะรัฐมนตรี ชุดที่ 65 (ชุดปัจจุบัน)

[ส่วนการลงมติ]
ปุ่มสีดำข้างล่าง ให้แสดง Text ว่า
1. ดูการลงมติของสมาชิกสภาผู้แทนราษฎร (สส.) ชุดที่ 25 (ชุดปัจจุบัน)
2. ดูการลงมติของสมาชิกวุฒิสภา (สว.) ชุดที่ 13 (ชุดปัจจุบัน)

**Screenshots**

Image

Image

**Additional context**
- Source code ที่แสดงหน้าแรก src/routes/+page.svelte

### PR DESCRIPTION
**Pull request by gunsodo**
# Related GitHub issues

Close #194 

## What have been done

Explicitly clarify the button text as described in #194.

## Screenshot (if any)

image

image

## Did you use AI in your PR? If so, how did you use AI, and what did you do to ensure the quality?

No

### CODE REVIEW

File: src/components/Index/VotingContent.svelte [hunk 1]
```diff
@@ -23,14 +23,14 @@
 		icon={ArrowRight}
 		class="w-full max-w-none"
 	>
-		ดูการลงมติทั้งหมดของสมาชิกสภาผู้แทนราษฎร ชุดที่ 26
+		ดูการลงมติของสมาชิกสภาผู้แทนราษฎร (สส.) ชุดที่ 26 (ชุดปัจจุบัน)
```
Comment (gunsodo) [inline src/components/Index/VotingContent.svelte:26]: @Th1nkK1D Please note that the prescribed fix in #194 that you mentioned in the PR description wrote "ชุดที่ 25" instead of 26. I decided to go with the latter and assumed you made a typo. Please let me know otherwise :)

**Comment by gunsodo** [comment]
@Th1nkK1D During the development, I experience a problem during pre-push hook due to your fix in [this commit](https://github.com/wevisdemo/parliament-watch/commit/673d68282772787f99f4067b1cf23abc8251fe72). Fixed locally by specifying the `PUBLIC_POLITIGRAPH_ENDPOINT` in the `.env` file manually since I couldn't find any treatment in the `REAMDE.md` nor `CONTRIBUTING.md`. Let me know if I could file another PR to explain this in the *Local development* section of `README.md` more clearly. And please ignore this comment if it is not a wise fix.
