### PR TITLE
fix: cabinet info

### LINKED ISSUE #130: Promise: Missing PM's profile photo
**Describe the bug**
The profile photo of PM is missing

**To Reproduce**
1. Go to https://promise-main.parliament-watch.pages.dev/promises

**Expected behavior**
The photo of the PM should be displayed

**Screenshots**
image

### PR DESCRIPTION
**Pull request by JaeAiKay**
# Related GitHub issues

Close #130 #131 #132 

## What have been done

- add filed avatar in prime minister for display in cabinet info (issue 130)
- display numbers of ministers of the parties (issue 131)
- add previous cabinet information (issue 132)

## Screenshot (if any)
before:
image
after:
image

### CODE REVIEW

File: src/components/Promise/Home/AboutCard.svelte [hunk 1]
```diff
@@ -59,21 +66,29 @@
...
 			<li class="label-01 ml-5">
-				นายกรัฐมนตรี{primeMinister.firstname}
-				{primeMinister.lastname} และคณะรัฐมนตรีจาก
-				{#each cabinet.cabinetMemberCountsByParty as party}
-					{#if typeof party.party != 'string'}
-						{party.party.name} ({party.count} ตำแหน่ง),&nbsp;
+				นายกรัฐมนตรี{previousCabinet.primeMinister.firstname}
+				{previousCabinet.primeMinister.lastname} และคณะรัฐมนตรีจาก
+				{#each Array.from({ length: previousCabinetMemberCountsByParty.length }, (_, i) => i) as i}
+					{@const party = previousCabinetMemberCountsByParty[i]}
```
Comment (Th1nkK1D) [inline src/components/Promise/Home/AboutCard.svelte:76]: I think you can turn these `each` and `const` into this which is more straightforward:
```svelte
{#each previousCabinetMemberCountsByParty as party, i}
```
Or I'm missing something?

File: src/routes/promises/+page.server.ts [hunk 2]
```diff
@@ -36,26 +42,36 @@ export interface PromisesByCategory {
 	count: number;
 }
 
+export type AssemblyMember = ReturnType<typeof getAssemblyMembers>[number];
+
 const CURRENT_CABINET_ASSEMBLY_ID = 'คณะรัฐมนตรี-64';
+const PREVIOUS_CABINET_ASSEMBLY_ID = 'คณะรัฐมนตรี-63';
```
Comment (Th1nkK1D) [inline src/routes/promises/+page.server.ts:48]: I think we should get rid of this hard code. Can you remove this constant here and then in the `load()`, you filter only "คณะรัฐมนตรี" name from the `assemblies`, sorted by term and then assign the latest 2 as current and previous cabinet?

File: src/routes/promises/+page.server.ts [hunk 3]
```diff
@@ -36,26 +42,36 @@ export interface PromisesByCategory {
...
+function findPrimeMinister(cabinetMembers: AssemblyMember[]) {
+	const primeMinister = cabinetMembers.find((m) => m.assemblyRole?.role === 'นายกรัฐมนตรี');
+	if (!primeMinister) {
+		error(500, `Cannot find the prime minister in the given cabinet`);
+	}
+	return primeMinister;
+}
 
-	const cabinetMembers = getAssemblyMembers(cabinetAssembly, politicians).filter(
+function getCainetMembers(cabinetAssembly: Assembly, politicians: Politician[]) {
```
Comment (Th1nkK1D) [inline src/routes/promises/+page.server.ts:66]: Typo here, should be `getCabinetMembers`

File: src/routes/promises/+page.server.ts [hunk 4]
```diff
@@ -36,26 +42,36 @@ export interface PromisesByCategory {
...
+	return getAssemblyMembers(cabinetAssembly, politicians).filter(
 		({ assemblyRole }) =>
 			!assemblyRole?.endedAt ||
 			(cabinetAssembly.endedAt && !dayjs(cabinetAssembly.endedAt).isAfter(assemblyRole.endedAt))
 	);
+}
 
+function getCabinetMemberCountsByParty(cabinetMembers: any[], parties: Party[]) {
```
Comment (Th1nkK1D) [inline src/routes/promises/+page.server.ts:74]: We should avoid using `any`. Following the codes, `cabinetMembers` should have the type `AssemblyMember` (imported from `$lib/datasheets/assembly-member`), Or something is not working here?

**Review by Th1nkK1D — APPROVED** [review]
LGTM! Thank you so much
