### PR TITLE
fix navbar on mobile does not close when changing to new page

### LINKED ISSUE #151: Navbar on mobile does not close when changing to new page
**Describe the bug**
When clicking a link in the navbar on a mobile screen, the user thinks the page has not changed because it was hidden under the full-screen navbar menu.

**To Reproduce**
1. Go to any page eg. https://parliamentwatch.wevis.info
2. Click on the hamburger menu to open the menu.
3. Click any link to go to any page.
4. The page is changed in the background, but it is not visible because the menu is still there.

**Expected behavior**
When user click the link, the navbar menu should be closed so users can see the pages has changed.

**Screenshots**

[Screencast from 2024-10-24 18-12-53.webm](https://github.com/user-attachments/assets/83318469-9c03-4d83-a857-6f5886b2278a)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox (capture on responsive mode)

**Additional context**
- Navigation bar component: `src/components/NavigationBar/NavigationBar.svelte`

### PR DESCRIPTION
**Pull request by SupeemAFK**
# Related GitHub issues

Close #151 

## What have been done

- Make the sidebar on mobile close when the user clicks on a menu list.

#### Before

[379742950-83318469-9c03-4d83-a857-6f5886b2278a.webm](https://github.com/user-attachments/assets/aaa2425d-08af-4b77-8bc5-68991c904ed0)

#### After

https://github.com/user-attachments/assets/7f0d4b8f-9b79-4dfa-b226-a571bb5c596e

### CODE REVIEW

**Review by Th1nkK1D — COMMENTED** [review]
The menu shouldn't close if user click the non-link item (in the rectangle)
image

If you look into `SideMenuList`, it doesn't always render the link. We want to emit the event from the exact element when users click and it navigated to the new page (so we can make sure that we only close the navbar when the page change) which is in `SideMenuList` > `SideMenuLink` > `a`

I suggest you remove unneccessary `Button` and use `onNavigate` callback props passing from `NavigationBar` to `SideMenuLink` where triggered by `a on:click`.

**Comment by SupeemAFK** [comment]
Fix it @Th1nkK1D . I pass down close sidebar function from `NavigationBar` component to `SideMenuLink` component using context to avoid props drilling so that  `a on:click` inside `SideMenuLink` component can call close sidebar function when clicked via context.

File: src/components/NavigationBar/SideMenuLink.svelte [hunk 1]
```diff
@@ -12,6 +15,7 @@
 	</div>
 {/if}
 <a
+	on:click={() => closeSideNav()}
```
Comment (Th1nkK1D) [inline src/components/NavigationBar/SideMenuLink.svelte:18]: Since `closeSideNav` didn't have any argument, no need to create a new arrow function. This should work:

```
on:click={closeSideNav}
```

File: src/components/NavigationBar/SideMenuLink.svelte [hunk 2]
```diff
@@ -2,6 +2,9 @@
 	import type { Menu } from '$models/menu';
 	import ArrowUpRightIcon from 'carbon-icons-svelte/lib/ArrowUpRight.svelte';
 	import { twMerge } from 'tailwind-merge';
+	import { getContext } from 'svelte';
+	const closeSideNav: () => void = getContext('closeSideNav');
```
Comment (Th1nkK1D) [inline src/components/NavigationBar/SideMenuLink.svelte:6]: Better move this variable below `export let`. Props is the most important information when anyone want to use components, so we better organize code that way.

**Review by Th1nkK1D — COMMENTED** [review]
Using context is also nice! I have some small feedback

**Comment by SupeemAFK** [comment]
Fix @Th1nkK1D. I change to `on:click={closeSideNav}` and move `const closeSideNav: () => void = getContext('closeSideNav');` below props.

**Review by Th1nkK1D — APPROVED** [review]
Great job! Thank you for your contributions :)
